apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: fluxDemo
  region: eu-central-1
  version: 1.33

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
managedNodeGroups:
  - name: demo-ng
    instanceType: t2.xlarge
    minSize: 2
    maxSize: 4
