apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flask-helm-app
  namespace: flask-helm-ns
spec:
  interval: 5m
  targetNamespace: flask-helm-ns
  chart:
    spec:
      chart: ./helm-charts/flask-helm-example    # relative path to your chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: 796618404628.dkr.ecr.eu-central-1.amazonaws.com/flask-hello
      tag: latest
    containerPort: 5000
    replicaCount: 2
